site_name: ThanoSQL
site_description: ThanoSQL Documentation
site_url: https://nokchalatte.github.io/thanosql-docs/
site_author: Smartmind Team

theme:
  name: material
  logo: assets/images/docs_logo.png
  favicon: assets/images/favicon.png
  custom_dir: overrides
  features:
    - navigation.expand # Default dropdown to expand
    - navigation.sections # At sidebar top-level section name with bold & not dropdown menu
    - navigation.tabs # Make top-level sections
    - navigation.tabs.sticky # Make top-level sections always visible
    - navigation.top # Enable back to top button
    - navigation.tracking # Enable the URL automatically updated with the active anchor as highlighted in the toc
    - search.highlight # Highlight all search result
    - search.suggest # Display the likeliest completion for the last word

plugins:
  - search # Built-in search plugin
  - mkdocs-jupyter: # Currently not using. If going to use, run pipenv install mkdocs-jupyter
      include_source: True # Enable download ipynb files
  # Multiple language versions
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en: English
        ko: 한국어
      nav_translations: # manage directory names
        en:
          Getting started: Getting Started
          Tutorials: Tutorials
          Thanosql search: ThanoSQL Search
          Thanosql ml: ThanoSQL ML
          How to guides: Reference
          ThanoSQL query: ThanoSQL Statement
          ThanoSQL connecting: REST API
          ThanoSQL model: Model Statement
          ThanoSQL function: Function Statement
          FAQ: FAQ
        ko:
          Getting started: 시작하기
          Tutorials: 튜토리얼
          Thanosql search: ThanoSQL Search
          Thanosql ml: ThanoSQL ML
          Classification: 분류 모델 만들기
          Regression: 회귀 모델 만들기
          Audio recognition: 음성 인식 모델 만들기
          Question answering: 질의 응답 모델 사용하기
          Timeseries: 시계열 모델 만들기
          How to guides: 참조
          ThanoSQL query: ThanoSQL Statement
          ThanoSQL connecting: REST API
          ThanoSQL model: Model Statement
          ThanoSQL function: Function Statement
          FAQ: 자주 묻는 질문
  - awesome-pages: # Omits nav and control over page
      strict: false # For ipynb tutorial folder
  # Adding the date of last update
  - git-revision-date-localized:
      type: iso_date # Format yyyy-mm-dd

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Git info
repo_name: nokchalatte/thanosql-docs
repo_url: https://github.com/nokchalatte/thanosql-docs
edit_uri: ""

extra:
  # Google Analytics
  analytics:
    provider: google
    property: G-8KVG4NMMFK
  generator: false # Hide "Made with Material for Mkdocs"

  # versioning
  version:
    provider: mike
    default: latest

extra_css:
  - assets/css/extra.css # For grid sections

copyright: "D-201, 39, Maeheon-ro 8-gil, Seocho-gu, Seoul 06770 South Korea<br />Email : contact@smartmind.team<br />Phone : (+82) 070-7151-9357<br /><br />© Since 2018 SmartMind, Inc. All Rights Reserved."